#https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote2-back1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote2-back1
  template:
    metadata:
      labels:
        app: azure-vote2-back1
    spec:
      containers:
      - name: azure-vote2-back1
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote2-back1
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote2-back1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote2-front1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote2-front1
  template:
    metadata:
      labels:
        app: azure-vote2-front1
    spec:
      containers:
      - name: azure-vote2-front1
        image: microsoft/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote2-back1"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote2-front1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "4"
#   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "svc"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote2-front1
